"""Refactor catalog product association

Revision ID: b0c52d7fd576
Revises: 29b5e8ac5384
Create Date: 2025-11-01 16:44:15.602796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c52d7fd576'
down_revision = '29b5e8ac5384'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_products')
    op.create_table('catalog_products',
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('catalog_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_products')
    op.create_table('catalog_products',
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('catalog_id', 'product_id')
    )
    # ### end Alembic commands ###
